### ISSUE TITLE
Licence unspecified

### ISSUE THREAD

**Issue by rzr** [lissyx/sensorweb-nodeMCU-PMS3003#1]
Please add a LICENSE file to repo

**Comment by lissyx** [comment]
Which one do you suggest @rzr ?

**Comment by rzr** [comment]
It's up to you, I would try to align to relevant project if any...

My preference is any SPDX/OSI/FSF approved licence

**Comment by lissyx** [comment]
I don't really care, I have no idea of relevant project either ... i'd go for MIT ...

**Comment by rzr** [comment]
fine for me or use ISC to prevent ambiguity between MIT versions
